#include "cpus/z80.hpp"

// Temporary: every dispatch slot is a 4-cycle unimplemented stub.

unsigned Z80::op40() { return opUnimplemented(); }
unsigned Z80::op41() { return opUnimplemented(); }
unsigned Z80::op42() { return opUnimplemented(); }
unsigned Z80::op43() { return opUnimplemented(); }
unsigned Z80::op44() { return opUnimplemented(); }
unsigned Z80::op45() { return opUnimplemented(); }
unsigned Z80::op46() { return opUnimplemented(); }
unsigned Z80::op47() { return opUnimplemented(); }
unsigned Z80::op48() { return opUnimplemented(); }
unsigned Z80::op49() { return opUnimplemented(); }
unsigned Z80::op4A() { return opUnimplemented(); }
unsigned Z80::op4B() { return opUnimplemented(); }
unsigned Z80::op4C() { return opUnimplemented(); }
unsigned Z80::op4D() { return opUnimplemented(); }
unsigned Z80::op4E() { return opUnimplemented(); }
unsigned Z80::op4F() { return opUnimplemented(); }
unsigned Z80::op50() { return opUnimplemented(); }
unsigned Z80::op51() { return opUnimplemented(); }
unsigned Z80::op52() { return opUnimplemented(); }
unsigned Z80::op53() { return opUnimplemented(); }
unsigned Z80::op54() { return opUnimplemented(); }
unsigned Z80::op55() { return opUnimplemented(); }
unsigned Z80::op56() { return opUnimplemented(); }
unsigned Z80::op57() { return opUnimplemented(); }
unsigned Z80::op58() { return opUnimplemented(); }
unsigned Z80::op59() { return opUnimplemented(); }
unsigned Z80::op5A() { return opUnimplemented(); }
unsigned Z80::op5B() { return opUnimplemented(); }
unsigned Z80::op5C() { return opUnimplemented(); }
unsigned Z80::op5D() { return opUnimplemented(); }
unsigned Z80::op5E() { return opUnimplemented(); }
unsigned Z80::op5F() { return opUnimplemented(); }
unsigned Z80::op60() { return opUnimplemented(); }
unsigned Z80::op61() { return opUnimplemented(); }
unsigned Z80::op62() { return opUnimplemented(); }
unsigned Z80::op63() { return opUnimplemented(); }
unsigned Z80::op64() { return opUnimplemented(); }
unsigned Z80::op65() { return opUnimplemented(); }
unsigned Z80::op66() { return opUnimplemented(); }
unsigned Z80::op67() { return opUnimplemented(); }
unsigned Z80::op68() { return opUnimplemented(); }
unsigned Z80::op69() { return opUnimplemented(); }
unsigned Z80::op6A() { return opUnimplemented(); }
unsigned Z80::op6B() { return opUnimplemented(); }
unsigned Z80::op6C() { return opUnimplemented(); }
unsigned Z80::op6D() { return opUnimplemented(); }
unsigned Z80::op6E() { return opUnimplemented(); }
unsigned Z80::op6F() { return opUnimplemented(); }
unsigned Z80::op70() { return opUnimplemented(); }
unsigned Z80::op71() { return opUnimplemented(); }
unsigned Z80::op72() { return opUnimplemented(); }
unsigned Z80::op73() { return opUnimplemented(); }
unsigned Z80::op74() { return opUnimplemented(); }
unsigned Z80::op75() { return opUnimplemented(); }
unsigned Z80::op76() { return opUnimplemented(); }
unsigned Z80::op77() { return opUnimplemented(); }
unsigned Z80::op78() { return opUnimplemented(); }
unsigned Z80::op79() { return opUnimplemented(); }
unsigned Z80::op7A() { return opUnimplemented(); }
unsigned Z80::op7B() { return opUnimplemented(); }
unsigned Z80::op7C() { return opUnimplemented(); }
unsigned Z80::op7D() { return opUnimplemented(); }
unsigned Z80::op7E() { return opUnimplemented(); }
unsigned Z80::op7F() { return opUnimplemented(); }
unsigned Z80::op80() { return opUnimplemented(); }
unsigned Z80::op81() { return opUnimplemented(); }
unsigned Z80::op82() { return opUnimplemented(); }
unsigned Z80::op83() { return opUnimplemented(); }
unsigned Z80::op84() { return opUnimplemented(); }
unsigned Z80::op85() { return opUnimplemented(); }
unsigned Z80::op86() { return opUnimplemented(); }
unsigned Z80::op87() { return opUnimplemented(); }
unsigned Z80::op88() { return opUnimplemented(); }
unsigned Z80::op89() { return opUnimplemented(); }
unsigned Z80::op8A() { return opUnimplemented(); }
unsigned Z80::op8B() { return opUnimplemented(); }
unsigned Z80::op8C() { return opUnimplemented(); }
unsigned Z80::op8D() { return opUnimplemented(); }
unsigned Z80::op8E() { return opUnimplemented(); }
unsigned Z80::op8F() { return opUnimplemented(); }
unsigned Z80::op90() { return opUnimplemented(); }
unsigned Z80::op91() { return opUnimplemented(); }
unsigned Z80::op92() { return opUnimplemented(); }
unsigned Z80::op93() { return opUnimplemented(); }
unsigned Z80::op94() { return opUnimplemented(); }
unsigned Z80::op95() { return opUnimplemented(); }
unsigned Z80::op96() { return opUnimplemented(); }
unsigned Z80::op97() { return opUnimplemented(); }
unsigned Z80::op98() { return opUnimplemented(); }
unsigned Z80::op99() { return opUnimplemented(); }
unsigned Z80::op9A() { return opUnimplemented(); }
unsigned Z80::op9B() { return opUnimplemented(); }
unsigned Z80::op9C() { return opUnimplemented(); }
unsigned Z80::op9D() { return opUnimplemented(); }
unsigned Z80::op9E() { return opUnimplemented(); }
unsigned Z80::op9F() { return opUnimplemented(); }
unsigned Z80::opA0() { return opUnimplemented(); }
unsigned Z80::opA1() { return opUnimplemented(); }
unsigned Z80::opA2() { return opUnimplemented(); }
unsigned Z80::opA3() { return opUnimplemented(); }
unsigned Z80::opA4() { return opUnimplemented(); }
unsigned Z80::opA5() { return opUnimplemented(); }
unsigned Z80::opA6() { return opUnimplemented(); }
unsigned Z80::opA7() { return opUnimplemented(); }
unsigned Z80::opA8() { return opUnimplemented(); }
unsigned Z80::opA9() { return opUnimplemented(); }
unsigned Z80::opAA() { return opUnimplemented(); }
unsigned Z80::opAB() { return opUnimplemented(); }
unsigned Z80::opAC() { return opUnimplemented(); }
unsigned Z80::opAD() { return opUnimplemented(); }
unsigned Z80::opAE() { return opUnimplemented(); }
unsigned Z80::opAF() { return opUnimplemented(); }
unsigned Z80::opB0() { return opUnimplemented(); }
unsigned Z80::opB1() { return opUnimplemented(); }
unsigned Z80::opB2() { return opUnimplemented(); }
unsigned Z80::opB3() { return opUnimplemented(); }
unsigned Z80::opB4() { return opUnimplemented(); }
unsigned Z80::opB5() { return opUnimplemented(); }
unsigned Z80::opB6() { return opUnimplemented(); }
unsigned Z80::opB7() { return opUnimplemented(); }
unsigned Z80::opB8() { return opUnimplemented(); }
unsigned Z80::opB9() { return opUnimplemented(); }
unsigned Z80::opBA() { return opUnimplemented(); }
unsigned Z80::opBB() { return opUnimplemented(); }
unsigned Z80::opBC() { return opUnimplemented(); }
unsigned Z80::opBD() { return opUnimplemented(); }
unsigned Z80::opBE() { return opUnimplemented(); }
unsigned Z80::opBF() { return opUnimplemented(); }
unsigned Z80::opC0() { return opUnimplemented(); }
unsigned Z80::opC1() { return opUnimplemented(); }
unsigned Z80::opC2() { return opUnimplemented(); }
unsigned Z80::opC3() { return opUnimplemented(); }
unsigned Z80::opC4() { return opUnimplemented(); }
unsigned Z80::opC5() { return opUnimplemented(); }
unsigned Z80::opC6() { return opUnimplemented(); }
unsigned Z80::opC7() { return opUnimplemented(); }
unsigned Z80::opC8() { return opUnimplemented(); }
unsigned Z80::opC9() { return opUnimplemented(); }
unsigned Z80::opCA() { return opUnimplemented(); }
unsigned Z80::opCB_prefix() { return opUnimplemented(); }
unsigned Z80::opCC() { return opUnimplemented(); }
unsigned Z80::opCD() { return opUnimplemented(); }
unsigned Z80::opCE() { return opUnimplemented(); }
unsigned Z80::opCF() { return opUnimplemented(); }
unsigned Z80::opD0() { return opUnimplemented(); }
unsigned Z80::opD1() { return opUnimplemented(); }
unsigned Z80::opD2() { return opUnimplemented(); }
unsigned Z80::opD3() { return opUnimplemented(); }
unsigned Z80::opD4() { return opUnimplemented(); }
unsigned Z80::opD5() { return opUnimplemented(); }
unsigned Z80::opD6() { return opUnimplemented(); }
unsigned Z80::opD7() { return opUnimplemented(); }
unsigned Z80::opD8() { return opUnimplemented(); }
unsigned Z80::opD9() { return opUnimplemented(); }
unsigned Z80::opDA() { return opUnimplemented(); }
unsigned Z80::opDB() { return opUnimplemented(); }
unsigned Z80::opDC() { return opUnimplemented(); }
unsigned Z80::opDD_prefix() { return opUnimplemented(); }
unsigned Z80::opDE() { return opUnimplemented(); }
unsigned Z80::opDF() { return opUnimplemented(); }
unsigned Z80::opE0() { return opUnimplemented(); }
unsigned Z80::opE1() { return opUnimplemented(); }
unsigned Z80::opE2() { return opUnimplemented(); }
unsigned Z80::opE3() { return opUnimplemented(); }
unsigned Z80::opE4() { return opUnimplemented(); }
unsigned Z80::opE5() { return opUnimplemented(); }
unsigned Z80::opE6() { return opUnimplemented(); }
unsigned Z80::opE7() { return opUnimplemented(); }
unsigned Z80::opE8() { return opUnimplemented(); }
unsigned Z80::opE9() { return opUnimplemented(); }
unsigned Z80::opEA() { return opUnimplemented(); }
unsigned Z80::opEB() { return opUnimplemented(); }
unsigned Z80::opEC() { return opUnimplemented(); }
unsigned Z80::opED_prefix() { return opUnimplemented(); }
unsigned Z80::opEE() { return opUnimplemented(); }
unsigned Z80::opEF() { return opUnimplemented(); }
unsigned Z80::opF0() { return opUnimplemented(); }
unsigned Z80::opF1() { return opUnimplemented(); }
unsigned Z80::opF2() { return opUnimplemented(); }
unsigned Z80::opF3() { return opUnimplemented(); }
unsigned Z80::opF4() { return opUnimplemented(); }
unsigned Z80::opF5() { return opUnimplemented(); }
unsigned Z80::opF6() { return opUnimplemented(); }
unsigned Z80::opF7() { return opUnimplemented(); }
unsigned Z80::opF8() { return opUnimplemented(); }
unsigned Z80::opF9() { return opUnimplemented(); }
unsigned Z80::opFA() { return opUnimplemented(); }
unsigned Z80::opFB() { return opUnimplemented(); }
unsigned Z80::opFC() { return opUnimplemented(); }
unsigned Z80::opFD_prefix() { return opUnimplemented(); }
unsigned Z80::opFE() { return opUnimplemented(); }
unsigned Z80::opFF() { return opUnimplemented(); }
